version: '2'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve -s /srv/jekyll/site -d /srv/jekyll/_site --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll/site
      - ./_site:/srv/jekyll/_site
