collections:
  factions:
    output: true
    permalink: /:collection/:name
  objects:
    output: true
    permalink: /:collection/:name
  people:
    output: true
    permalink: /:collection/:name
  places:
    output: true
    permalink: /:collection/:name
