base-url: /dndkc

defaults:
  - scope:
      path: 'dndkc/factions'
    values:
      layout: "default.html"

collections:
  factions:
    output: true
  objects:
    output: true
  people:
    output: true
  places:
    output: true
