base-url: /dndkc

defaults:
  - scope:
      path: 'factions'
      type: "pages"

collections:
  factions:
    output: true
  objects:
    output: true
  people:
    output: true
  places:
    output: true

theme: jekyll-theme-minimal