base-url: /dndkc

defaults:
  - scope:
      path: 'factions'
    values:
      layout: 'page'

collections:
  factions:
    output: true
  objects:
    output: true
  people:
    output: true
  places:
    output: true

theme: jekyll-theme-minimal