baseurl: /dndkc

category-list: [faction, object, campaign, people, place, crafting, recipe, technology]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"

theme: jekyll-theme-modernist