base-url: /dndkc

defaults:
  - scope:
      path: ''
    values:
      layout: ~
collections:
  factions:
    output: true
    layout: default
  objects:
    output: true
  people:
    output: true
  places:
    output: true

theme: jekyll-theme-minimal